package homework.ten;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Circle2D.java
//  @ Date : 2020/4/12
//  @ Author : 
//
//




public class Circle2D {
	private double x;
	private double y;
	private double radius;

	public Circle2D() {
		this.x=0;
		this.y=0;
		this.radius=1;
	}

	public Circle2D(double x, double y, double radius) {
		this.x = x;
		this.y = y;
		this.radius = radius;
	}

	public double getRadius() {
		return radius;
	}

	public double getX() {
		return x;
	}

	public void setX(double x) {
		this.x = x;
	}

	public double getY() {
		return y;
	}

	public void setY(double y) {
		this.y = y;
	}

	public double getArea() {
	return Math.PI*radius*radius;
	}
	
	public double getPerimeter() {
	return 2*Math.PI*radius;
	}

	public double distance(double x,double y){
		//计算点与圆心之间的距离
		double distance=Math.sqrt((x*x-this.x*this.x)+(y*y-this.y*this.y));
		return distance;
	}
	public boolean contains(double x, double y) {
	if (distance(x,y)<this.radius)
		return true;
	return false;
	}

	public boolean contains(Circle2D circle) {
	if (circle.distance(x,y)<this.radius&&circle.getArea()<this.getArea())
		return true;
	return false;
	}

	public boolean overlaps(Circle2D circle) {
	if (circle.distance(x,y)>this.radius&&circle.distance(x,y)<this.radius+circle.radius)
		return true;
	return false;
	}
}
