package homework.ten;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MyInterger.java
//  @ Date : 2020/4/15
//  @ Author : 
//
//




public class MyInteger {
	private int value;

	public MyInteger(int value) {
		this.value = value;
	}

	public int getValue() {
		return value;
	}

	public boolean isEven() {
		return isEven(value);
	}
	
	public static boolean isEven(int value) {
		if (value==1)
			return false;
		else if (value%2==0)
			return true;
		else return false;
	}
	
	public static boolean isEven(MyInteger myInteger) {
		if (myInteger.getValue()==1)
			return false;
		if (myInteger.getValue()%2==0)
			return true;
		else return false;
	}
	
	public boolean isOdd() {
		return isOdd(value);
	}
	
	public static boolean isOdd(int value) {
		if (value==2||value==0)
			return false;
		else if (value%2!=0)
			return true;
		else return false;
	}
	
	public static boolean isOdd(MyInteger myInterger) {
		if (myInterger.getValue()==2||myInterger.getValue()==0)
			return false;
		if (myInterger.getValue()%2!=0)
			return true;
		else return false;
	}
	
	public boolean isPrime() {
		return isPrime(value);
	}
	
	public static boolean isPrime(int value) {
		if (value==1||value==2)
			return true;
		for (int i=2;i<value;i++){
			if (value%i==0)
				return false;
		}
		return true;
	}


	public static boolean isPrime(MyInteger myInteger) {
		for (int i=2;i<myInteger.getValue();i++){
			if (myInteger.getValue()%i==0)
				return false;
		}
		return false;
	}
	
	public boolean equals(int num) {
		if (value==num)
			return true;
		else return false;
	}
	
	public boolean equals(MyInteger myInteger) {
		if (value==myInteger.getValue())
			return true;
		else return false;
	}
	
	public static int parseInt(char[] ch) {
		int parseInt=0;
		int temp=0;
		for (int i=0;i<ch.length;i++){
			parseInt*=10;
			//数字字符的ASCII码0为48
			temp=Integer.valueOf(ch[i]-'0');
			parseInt+=temp;
		}
		return parseInt;
	}
	
	public static int parseInt(String s) {
		int paresInt=0;
		paresInt=Integer.valueOf(s);
		return paresInt;
	}
}
