package homework.ten;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MyRectngle2D.java
//  @ Date : 2020/4/15
//  @ Author : 
//
//




public class MyRectangle2D {
	private double x;
	private double y;
	private double width;
	private double height;

	public MyRectangle2D() {
		this.x=0;
		this.y=0;
		this.width=1;
		this.height=1;
	}

	public MyRectangle2D(double x, double y, double width, double height) {
		this.x = x;
		this.y = y;
		this.width = width;
		this.height = height;
	}

	public double getArea() {
		return width*height;
	}
	
	public double getPerimeter() {
		return 2*(width+height);
	}

	//确定四个顶点的坐标
	double x1=x-width/2;
	double x2=x+width/2;
	double x3=x-width/2;
	double x4=x+width/2;

	double y1=y+height/2;
	double y2=y+height/2;
	double y3=y-height/2;
	double y4=y-height/2;

	public boolean contains(double x, double y) {
	if (Math.abs(x-this.x)<width/2&&Math.abs(y-this.y)<height/2)
		return true;
	else return false;
	}

	public double getX() {
		return x;
	}

	public void setX(double x) {
		this.x = x;
	}

	public double getY() {
		return y;
	}

	public void setY(double y) {
		this.y = y;
	}

	public double getWidth() {
		return width;
	}

	public void setWidth(double width) {
		this.width = width;
	}

	public double getHeight() {
		return height;
	}

	public void setHeight(double height) {
		this.height = height;
	}

	public boolean contains(MyRectangle2D r) {
	if (r.x<x2-r.width/2&&r.x>x1+r.width/2&&r.y<y1-r.height/2&&r.y>y3+r.height/2)
		return true;
	else return false;
	}
	
	public boolean overlaps(MyRectangle2D r) {
	if (contains(r))
		return false;
	else return true;
	}
}
