package homework.eleven;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Course.java
//  @ Date : 2020/4/20
//  @ Author : 
//
//


import java.util.ArrayList;

public class Course {
	private String courseName;
	private ArrayList<String> students=new ArrayList<String>(100);
	private int numberOfStudents;

	public String getCourseName() {
		return courseName;
	}

	public ArrayList getStudents() {
		return students;
	}

	public int getNumberOfStudents() {
		return numberOfStudents;
	}

	public Course(String courseName) {
		this.courseName = courseName;
	}

	public void addStudent(String student) {
		students.add(student);
		numberOfStudents++;
	}
	
	public void dropStudent(String student) {
	students.remove(student);
	numberOfStudents--;
	}

	@Override
	public String toString() {
		return ""+students;
	}
}
