package homework.eleven;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : GeometricObject.java
//  @ Date : 2020/4/20
//  @ Author : 
//
//


import java.util.Date;

public class GeometricObject {
	public String color="没有设置颜色";
	public boolean filled;

	public GeometricObject() {
	}

	public GeometricObject(String color, boolean filled) {
		this.color = color;
		this.filled = filled;
	}

	public String getColor() {
		return color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	public void setFilled(boolean filled) {
		this.filled = filled;
	}

	public boolean isFilled() {
		return filled;
	}

	public  java.util.Date getDateCreated(){
		Date date=new Date();
		return date;
	}

	@Override
	public String toString() {
		return "GeometricObject{" +
				"color='" + color + '\'' +
				", filled=" + filled +
				'}';
	}
}
