package homework.thirteen;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : TestComplex.java
//  @ Date : 2020/5/10
//  @ Author : 
//
//

import java.util.Scanner;

public class TestComplex{
	public static void main(String[] args) {
		Scanner input=new Scanner(System.in);
		System.out.print("Enter the first complex number:");
		double a=input.nextDouble();
		double b=input.nextDouble();
		Complex c1=new Complex(a,b);
		System.out.print("Enter the second complex number:");
		double c=input.nextDouble();
		double d=input.nextDouble();
		Complex c2=new Complex(c,d);
		Complex cAdd=c1.add(c2.getA(),c2.getB());
		Complex cSub=c1.substract(c2.getA(),c2.getB());
		Complex cMul=c1.multiply(c2.getA(),c2.getB());
		Complex cDiv=c1.divide(c2.getA(),c2.getB());
		System.out.println("("+c1.getA()+" + "+c1.getB()+"i) +"+" ("+c2.getA()+" + "+c2.getB()+"i) = "+c1.add(c2.getA(),c2.getB()).getA()+" + "+c1.add(c2.getA(),c2.getB()).getB()+"i");
		System.out.println("("+c1.getA()+" + "+c1.getB()+"i) -"+" ("+c2.getA()+" + "+c2.getB()+"i) = "+c1.substract(c2.getA(),c2.getB()).getA()+" + "+c1.substract(c2.getA(),c2.getB()).getB()+"i");
		System.out.println("("+c1.getA()+" + "+c1.getB()+"i) *"+" ("+c2.getA()+" + "+c2.getB()+"i) = "+c1.multiply(c2.getA(),c2.getB()).getA()+" + "+c1.multiply(c2.getA(),c2.getB()).getB()+"i");
		System.out.println("("+c1.getA()+" + "+c1.getB()+"i) /"+" ("+c2.getA()+" + "+c2.getB()+"i) = "+c1.divide(c2.getA(),c2.getB()).getA()+" + "+c1.divide(c2.getA(),c2.getB()).getB()+"i");
		System.out.println("|("+c1.getA()+"+"+c1.getB()+"i)| = "+c1.abs());
	}



}


class Complex {
	private double a;
	private double b;

	public Complex(double a, double b) {
		this.a = a;
		this.b = b;
	}

	public Complex(double a) {
		this.a = a;
		this.b=0;
	}

	public Complex() {
		a=0;
		b=0;
	}

	public Complex add(double a, double b){
	double a1=this.a+a;
	double b1=this.b+b;
	return new Complex(a1,b1);
	}
	
	public Complex substract(double a, double b) {
		double a1=this.a-a;
		double b1=this.b-b;
		return new Complex(a1,b1);
	}
	
	public Complex multiply(double a, double b) {
		double a1=this.a*a-this.b*b;
		double b1=this.b*a+this.a*b;
		return new Complex(a1,b1);
	}
	
	public Complex divide(double a, double b) {
		double a1=(this.a*a+this.b*b)/(a*a+b*b);
		double b1=(this.b*a-this.a*b)/(a*a+b*b);
		return new Complex(a1,b1);
	}
	
	public double abs() {
	return Math.sqrt(a*a+b*b);
	}
	
	public double getRealPart(Complex c) {
	return a+c.a;
	}
	
	public double getImagePart(Complex c) {
	return b+c.b;
	}

	public double getA() {
		return a;
	}

	public double getB() {
		return b;
	}

}
