package homework.nine;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Account.java
//  @ Date : 2020/4/8
//  @ Author : 
//
//

import java.util.Date;


public class Account {
	private int id;
	private double balance;
	private double annualInterestRate;
	private Date dateCreated;

	//无参构造方法
	public Account() {
		dateCreated=new Date();
	}
	//指定参数构造方法
	public Account(int id, double balance) {
		this.id = id;
		this.balance = balance;
		dateCreated=new Date();
	}
	//访问开户日期
	public Date getDateCreated() {
		return dateCreated;
	}
	//访问ID
	public int getId() {
		return id;
	}
	//设置ID
	public void setId(int id) {
		this.id = id;
	}
	//访问余额
	public double getBalance() {
		return balance;
	}
	//设置余额
	public void setBalance(double balance) {
		this.balance = balance;
	}
	//访问年利率
	public double getAnnualInterestRate() {
		return annualInterestRate;
	}
	//设置年利率
	public void setAnnualInterestRate(double annualInterestRate) {
		this.annualInterestRate = annualInterestRate;
	}
	//访问月利率
	public double getMonthlyInterestRate() {
	return annualInterestRate/100/12;
	}
	//访问月利息
	public double getMonthlyInterest() {
	return balance*getMonthlyInterestRate();
	}
	//取钱
	public double withDraw(double out) {
		return balance-=out;
	}
	//存钱
	public double deposit(double in) {
		return balance+=in;
	}

	@Override
	public String toString() {
		return "Account{" +
				"id=" + id +
				", balance=" + balance +
				", annualInterestRate=" + annualInterestRate +
				", dateCreated=" + dateCreated +
				'}';
	}
}
