package homework.nine;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Location.java
//  @ Date : 2020/4/8
//  @ Author : 
//
//




public class Location {
	public int row;
	public int column;
	public double maxValue;
}
