package homework.nine;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Rectangle.java
//  @ Date : 2020/4/7
//  @ Author : 
//
//




public class Rectangle {
	double width=1;
	double height=1;

	public Rectangle() {
	}

	public Rectangle(double width, double height) {
		this.width = width;
		this.height = height;
	}

	public double getArea() {
	return width*height;
	}
	
	public double getPerimeter() {
	return 2*(width+height);
	}
}
