package homework.nine;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : RegularPolygon.java
//  @ Date : 2020/4/8
//  @ Author : 
//
//




public class RegularPolygon {
	private int n=3;//多边形的边数
	private double side=1;//边的长度
	private double x;//多边形中点的x坐标
	private double y;//多边形中点y的坐标

	public RegularPolygon() {
		//无参构造方法
	}
	//指定边数和边长，中心在（0,0）的构造方法
	public RegularPolygon(int n, double side) {
		this.n = n;
		this.side = side;
	}
	//指定边数和边长，中心在（x,y）的构造方法
	public RegularPolygon(int n, double side, double x, double y) {
		this.n = n;
		this.side = side;
		this.x = x;
		this.y = y;
	}

	public int getN() {
		return n;
	}

	public void setN(int n) {
		this.n = n;
	}

	public double getSide() {
		return side;
	}

	public void setSide(double side) {
		this.side = side;
	}

	public double getX() {
		return x;
	}

	public void setX(double x) {
		this.x = x;
	}

	public double getY() {
		return y;
	}

	public void setY(double y) {
		this.y = y;
	}

	public double getPerimeter() {
		return n*side;
	}
	
	public double getArea() {
	return n*side*side/(4*Math.tan(Math.PI/n));
	}
}
